### ISSUE TITLE
[feat]: add the SaaS Template of Magic UI

### ISSUE THREAD

**Issue by RanNahmany** [nyxb-ui/ui#10]
### Feature description

it's been released!!!! would you plz add it ?
it also has some new components

### Affected component/components

Templates

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by RanNahmany** [comment]
@nyxb

**Comment by nyxb** [comment]
I’m currently managing the project on my own and my time is quite limited at the moment. I don’t simply copy and paste code. Instead, I identify the styles and functionalities and build everything manually. However, I will make every effort to ensure the quality of the work, and contributions are always welcome.
