### ISSUE TITLE
[bug]: Installation guide for Vite has an error

### ISSUE THREAD

**Issue by MarkyJD** [nyxb-ui/ui#17]
### Describe the bug

In the 'Update vite.config.ts' section, the alias isn't set correctly. It should be '@' instead of `~`. [https://nyxbui.design/docs/installation/vite#update-viteconfigts](url)

### Affected component/components

Docs

### How to reproduce

Follow the Vite installation docs

### System Info

```bash
n/a
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by nyxb** [comment]
ok will look

**Comment by nyxb** [comment]
done
