### ISSUE TITLE
[bug]: Can't Add Any UI element

### ISSUE THREAD

**Issue by AbdellahDev64** [nyxb-ui/ui#19]
### Describe the bug

When try to install any ui element in **NEXT JS**, I get :
> npx nyxb@latest add checkbox

✔ Checking registry.
✔ Installing dependencies.
⠹ Updating files.

Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

The component at https://nyxbui.design/r/colors/blue.json was not found.
It may not exist at the registry. Please make sure it is a valid component.

### Affected component/components

Every Component

### How to reproduce

Just Try To Install any ui element using 
> npx nyxb@latest add ui-element

### System Info

```bash
I tried it in Windows 10 Entreprise 10.0.19045 Build 19045

npm -v -> 10.8.2
node -v -> v22.5.1
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [x] I've searched for existing issues

**Comment by nyxb** [comment]
look here pls: https://nyxbui.design/docs/changelog

**Comment by ChrisBryann** [comment]
Hello, I've reviewed the changelogs and found nothing to help me fix this issue.
