### ISSUE TITLE
[bug]: page not found for animated circular progress bar in docs

### ISSUE THREAD

**Issue by xambassador** [nyxb-ui/ui#21]
### Describe the bug

When trying to access [Animated circular progress bar](https://nyxbui.design/docs/components/animated-circular-progress-bar) component documentation, it is showing page not found.

### Affected component/components

Animated circular progress bar

### How to reproduce

Go to [Animated circular progress bar](https://nyxbui.design/docs/components/animated-circular-progress-bar).

### Codesandbox/StackBlitz link

https://nyxbui.design/docs/components/animated-circular-progress-bar

### System Info

```bash
Arc Version 1.66.0 (55166)
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by nyxb** [comment]
Thanks for reporting the bug with the Animated Circular Progress Bar documentation. The issue has been fixed and the page is now working properly.
