### ISSUE TITLE
[bug]: In Miami style, the combobox drop-down box cannot be selected

### ISSUE THREAD

**Issue by simman** [nyxb-ui/ui#23]
### Describe the bug

https://github.com/user-attachments/assets/b772c475-550f-4978-a635-3e547aa6d4a9

### Affected component/components

Combobox

### How to reproduce

1

### System Info

```bash
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by nyxb** [comment]
Thank you for your bug report. The Combobox issue has been fixed.
