### ISSUE TITLE
[bug]: Duplicate Neon-Gradient-Card installation component

### ISSUE THREAD

**Issue by Admeen3581** [nyxb-ui/ui#24]
### Describe the bug

Visual website bug such that when you try to get the manual installation for 'Neon-Gradient-Card' on the website, it will give you two of the same component making it somewhat confusing. Visual bug, nothing functional. Minor.

### Affected component/components

Neon-Gradient-Card

### How to reproduce

Go to https://nyxbui.design/docs/components/neon-gradient-card.

Scroll to installation

Click 'Manual'

Click 'Expand'

*if you scroll long enough you'll see a duplicate installation component on the website.*

### Codesandbox/StackBlitz link

https://nyxbui.design/docs/components/neon-gradient-card

### Logs

```bash
N/A
```

### System Info

```bash
Dell XPS 13 9310 - Windows 10 - Brave Browser Version 1.73.89 Chromium: 131.0.6778.69 (Official Build) (64-bit)
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by nyxb** [comment]
Thank you for reporting this visual duplication issue with the Neon-Gradient-Card manual installation section. I'm happy to inform you that the bug has been fixed - there's no longer a duplicate component showing up in the documentation. Your detailed bug report helped us identify and resolve the problem quickly. Thanks for helping improve the documentation! 🙌

**Comment by Admeen3581** [comment]
Glad to help :).
