### ISSUE TITLE
[bug]: Validation Failed for Style and Tailwind Configuration during initialization

### ISSUE THREAD

**Issue by Peyu5h** [nyxb-ui/ui#25]
### Describe the bug

When initializing a project using `npx nyxb@latest init`, the process fails during the validation phase with the error:

![image](https://github.com/user-attachments/assets/b2226f2a-345f-45b5-b59f-69356d5b5ca8)

### Affected component/components

All

### How to reproduce

1. Run `npx nyxb@latest init` in a terminal with a valid Next.js project.
2. Observe the error during the validation stage.

### System Info

```bash
nodejs version: 20.11.0
nextjs version: 15.0.3 and older
React Version: ^18
Tailwind CSS Version: ^3.4.1
TypeScript Version: ^5
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by nyxb** [comment]
try it now again pls
