### ISSUE TITLE
[feat]: can you complete the docs components? like tooltip, switch, toggle, etc...

### ISSUE THREAD

**Issue by Walidnurudin** [nyxb-ui/ui#27]
### Feature description

I want to use this lib, but some documentation not complete filled, like preview & code not showing.

example: https://nyxbui.design/docs/components/switch

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by ferrianes** [comment]
yeah, this is feel disgusting

**Comment by ferrianes** [comment]
yeah thats annoying

**Comment by nyxb** [comment]
I believe I've fixed them all, but if you notice any others, please create a new issue. Thank you.
